/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Listagem;

import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import telas.Manutencao.Lavoura;

/**
 *
 * @author itzfeltrin
 */
public class ListagemLavouraDetalhada extends javax.swing.JFrame {

    private int codigo;
    private String nome;
    /**
     * 
     * Creates new form ListagemLavouraDetelhada
     */
    public ListagemLavouraDetalhada(int codigo, String nome) {
        try {
            initComponents();
            setResizable(false);
            setLocationRelativeTo(null);        
            this.codigo = codigo;
            this.nome = nome;

            //Color color = Color.decode("#add8e6");        
            //this.getContentPane().setBackground(color);

            lblNome.setText("Lavoura " + nome);
            
            
            atualizarTabelaPlanta();
            atualizarTabelaProdutividade();
            atualizarTabelaAplicacao();
        }
        catch (Exception ex){
            
        }
    }

    private ListagemLavouraDetalhada() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutividade = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAplicacaoDefensivos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaPlantas = new javax.swing.JTable();
        lblLogo = new javax.swing.JLabel();
        tabelaDefDelete = new javax.swing.JLabel();
        tabelaDefEdit = new javax.swing.JLabel();
        tabelaDefNew = new javax.swing.JLabel();
        tabelaProNew = new javax.swing.JLabel();
        tabelaProEdit = new javax.swing.JLabel();
        tabelaProDelete = new javax.swing.JLabel();
        tabelaPlaDelete = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("Produtividade");

        jLabel2.setText("Plantas");

        tabelaProdutividade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaProdutividade);

        tabelaAplicacaoDefensivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaAplicacaoDefensivos);

        jLabel3.setText("Aplicação de Defensivos");

        tabelaPlantas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelaPlantas);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agro202.png"))); // NOI18N

        tabelaDefDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteicon(3).png"))); // NOI18N
        tabelaDefDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaDefDeleteMousePressed(evt);
            }
        });

        tabelaDefEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editicon(1).png"))); // NOI18N
        tabelaDefEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaDefEditMousePressed(evt);
            }
        });

        tabelaDefNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plusicon(1).png"))); // NOI18N
        tabelaDefNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaDefNewMousePressed(evt);
            }
        });

        tabelaProNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plusicon(1).png"))); // NOI18N
        tabelaProNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaProNewMousePressed(evt);
            }
        });

        tabelaProEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editicon(1).png"))); // NOI18N
        tabelaProEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaProEditMousePressed(evt);
            }
        });

        tabelaProDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteicon(3).png"))); // NOI18N
        tabelaProDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaProDeleteMousePressed(evt);
            }
        });

        tabelaPlaDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteicon(3).png"))); // NOI18N
        tabelaPlaDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaPlaDeleteMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tabelaProNew, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tabelaProEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tabelaProDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(tabelaPlaDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(tabelaDefNew, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tabelaDefEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tabelaDefDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(157, 157, 157)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tabelaProDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE)
                                .addComponent(tabelaProEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tabelaProNew, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                            .addComponent(tabelaPlaDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(tabelaDefNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabelaDefEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabelaDefDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogo)
                        .addGap(14, 14, 14)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tabelaDefEdit, tabelaProDelete, tabelaProEdit, tabelaProNew});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void tabelaProDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProDeleteMousePressed
        if(tabelaProdutividade.getSelectedRow() >= 0){
            Object[] options = {"Não", "Sim"};
            int opcao = JOptionPane.showOptionDialog(null, "Tem certeza?", "Alerta", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if(opcao == 1){
                int linhaSelecionada = tabelaProdutividade.getSelectedRow();        
                int codigo = Integer.parseInt(tabelaProdutividade.getValueAt(linhaSelecionada, 0).toString());
                dao.ProdutividadeDao.deletar(codigo);            
                atualizarTabelaProdutividade();
            }
        }
    }//GEN-LAST:event_tabelaProDeleteMousePressed

    private void tabelaPlaDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPlaDeleteMousePressed
        if(tabelaPlantas.getSelectedRow() >= 0){
            Object[] options = {"Não", "Sim"};
            int opcao = JOptionPane.showOptionDialog(null, "Tem certeza?", "Alerta", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if(opcao == 1){
                int linhaSelecionada = tabelaPlantas.getSelectedRow();        
                int codigo_planta = Integer.parseInt(tabelaPlantas.getValueAt(linhaSelecionada, 0).toString());
                String data = tabelaPlantas.getValueAt(linhaSelecionada, 1).toString();
                try {
                    dao.LavouraPlantaDao.deletar(this.codigo, codigo_planta, data);
                    atualizarTabelaPlanta();
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
                }
                
            }
        }
    }//GEN-LAST:event_tabelaPlaDeleteMousePressed

    private void tabelaDefDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDefDeleteMousePressed
        if(tabelaAplicacaoDefensivos.getSelectedRow() >= 0){
            Object[] options = {"Não", "Sim"};
            int opcao = JOptionPane.showOptionDialog(null, "Tem certeza?", "Alerta", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if(opcao == 1){
                int linhaSelecionada = tabelaAplicacaoDefensivos.getSelectedRow();        
                int codigo_aplicacao = Integer.parseInt(tabelaAplicacaoDefensivos.getValueAt(linhaSelecionada, 0).toString());                
                try {
                    dao.AplicacaoDefensivoDao.deletar(codigo_aplicacao);
                    atualizarTabelaAplicacao();
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
                }
                
            }
        }
    }//GEN-LAST:event_tabelaDefDeleteMousePressed

    private void tabelaProNewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProNewMousePressed
        Lavoura lav;
        try {
            lav = new Lavoura(null, true, this, this.codigo);
            lav.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ListagemLavoura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabelaProNewMousePressed

    private void tabelaProEditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProEditMousePressed
        if(tabelaProdutividade.getSelectedRow() >= 0){            
            int linhaSelecionada = tabelaProdutividade.getSelectedRow();        
            int codigo_produtividade = Integer.parseInt(tabelaProdutividade.getValueAt(linhaSelecionada, 0).toString());
            int qtd_sacas = Integer.parseInt(tabelaProdutividade.getValueAt(linhaSelecionada, 1).toString());
            Short safra = Short.parseShort(tabelaProdutividade.getValueAt(linhaSelecionada, 2).toString());
            int cod_planta = Integer.parseInt(tabelaProdutividade.getValueAt(linhaSelecionada, 3).toString());            
            try {
                Lavoura lav = new Lavoura(null, true, this, this.codigo, codigo_produtividade, qtd_sacas, safra, cod_planta);
                lav.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(ListagemLavoura.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tabelaProEditMousePressed

    private void tabelaDefNewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDefNewMousePressed
        try {
            Lavoura lav = new Lavoura(null, true, this, this.codigo, 'a');
            lav.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ListagemLavoura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabelaDefNewMousePressed

    private void tabelaDefEditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDefEditMousePressed
        if(tabelaAplicacaoDefensivos.getSelectedRow() >= 0){
            int linhaSelecionada = tabelaAplicacaoDefensivos.getSelectedRow();
            int codigo_aplicacao = Integer.parseInt(tabelaAplicacaoDefensivos.getValueAt(linhaSelecionada, 0).toString());
            String date = tabelaAplicacaoDefensivos.getValueAt(linhaSelecionada, 1).toString();
            int codigo_defensivo = Integer.parseInt(tabelaAplicacaoDefensivos.getValueAt(linhaSelecionada, 2).toString());
            Double dose = Double.parseDouble(tabelaAplicacaoDefensivos.getValueAt(linhaSelecionada, 3).toString());
            try {
                Lavoura lav = new Lavoura(null, true, this, this.codigo, codigo_aplicacao, date, codigo_defensivo, dose);
                lav.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(ListagemLavoura.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tabelaDefEditMousePressed

    public void atualizarTabelaPlanta() {
        DefaultTableModel modelo = new DefaultTableModel();        
        modelo.addColumn("Código");        
        modelo.addColumn("Data do Plantio");
        modelo.addColumn("Tipo");
        modelo.addColumn("Cultivar");
        List<String[]> resultados = dao.LavouraPlantaDao.consultar(this.codigo);
        for (String[] linha : resultados) {
            modelo.addRow(linha);
        }
        tabelaPlantas.setModel(modelo);
    }
    
    public void atualizarTabelaProdutividade() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Qtd. Sacas");
        modelo.addColumn("Safra");
        modelo.addColumn("Cod. Planta");
        //modelo.addColumn("Tipo");
        //modelo.addColumn("Cultivar");
        List<String[]> resultados = dao.ProdutividadeDao.consultar(this.codigo);
        for (String[] linha : resultados) {
            modelo.addRow(linha);
        }
        tabelaProdutividade.setModel(modelo);        
    }
    
    public void atualizarTabelaAplicacao() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Data");
        modelo.addColumn("Cód. Defensivo");                
        modelo.addColumn("Dose");
        modelo.addColumn("Nome");
        modelo.addColumn("Classe");
        List<String[]> resultados = dao.AplicacaoDefensivoDao.consultar(this.codigo);
        for (String[] linha : resultados) {
            modelo.addRow(linha);
        }
        tabelaAplicacaoDefensivos.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemLavouraDetalhada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemLavouraDetalhada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemLavouraDetalhada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemLavouraDetalhada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListagemLavouraDetalhada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTable tabelaAplicacaoDefensivos;
    private javax.swing.JLabel tabelaDefDelete;
    private javax.swing.JLabel tabelaDefEdit;
    private javax.swing.JLabel tabelaDefNew;
    private javax.swing.JLabel tabelaPlaDelete;
    private javax.swing.JTable tabelaPlantas;
    private javax.swing.JLabel tabelaProDelete;
    private javax.swing.JLabel tabelaProEdit;
    private javax.swing.JLabel tabelaProNew;
    private javax.swing.JTable tabelaProdutividade;
    // End of variables declaration//GEN-END:variables
}
