/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Main;

/**
 *
 * @author itzfeltrin
 */
public class PanelLogin extends javax.swing.JPanel {

    private javax.swing.JTabbedPane parentPane;
    
    /**
     * Creates new form PanelLogin
     */
    public PanelLogin(javax.swing.JTabbedPane mainTabbedPane) {
        initComponents();
        this.parentPane = mainTabbedPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUser = new javax.swing.JTextField();
        lblSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        add(jLabel1);
        jLabel1.setBounds(10, 11, 667, 120);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("Usuário:");
        add(jLabel2);
        jLabel2.setBounds(130, 137, 63, 25);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setText("Senha:");
        add(jLabel3);
        jLabel3.setBounds(130, 168, 63, 27);
        add(lblUser);
        lblUser.setBounds(197, 137, 360, 25);
        add(lblSenha);
        lblSenha.setBounds(197, 168, 360, 27);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setText("ENTRAR");
        jButton1.setOpaque(false);
        jButton1.setSelected(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(197, 201, 360, 40);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Novo Cadastro?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(377, 259, 180, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.parentPane.setSelectedIndex(1);        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void login(){
        if(lblUser.getText().length() == 0){
            System.out.println("O campo de usuário não pode ficar vazio!");
        }
        else {
            if(lblSenha.getPassword().length == 0){
                System.out.println("O campo de senha não pode ficar vazio!");
            }
            else {                
                this.parentPane.add("Home", new PanelAfterLogin(lblUser.getText()));
                this.parentPane.setSelectedIndex(2);
                this.parentPane.setEnabledAt(0, false);                
                this.parentPane.setEnabledAt(1, false);                
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField lblSenha;
    private javax.swing.JTextField lblUser;
    // End of variables declaration//GEN-END:variables
}
