/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Main;

import dao.UserDao;
import javax.swing.JOptionPane;
import org.postgresql.util.PSQLException;

/**
 *
 * @author itzfeltrin
 */
public class PanelCadastro extends javax.swing.JPanel {

    private javax.swing.JTabbedPane parentPane;
    /**
     * Creates new form PanelCadastro
     */
    public PanelCadastro(javax.swing.JTabbedPane mainTabbedPane) {
        initComponents();
        this.parentPane = mainTabbedPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUser = new javax.swing.JTextField();
        lblSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblConfSenha = new javax.swing.JPasswordField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 667, 97));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("Usuário:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 160, 63, 25));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setText("Senha:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 190, 49, 27));
        add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 360, 25));
        add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 360, 27));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setText("CADASTRAR");
        jButton1.setOpaque(false);
        jButton1.setSelected(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 360, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nome:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 128, 64, 25));
        add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 360, 25));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setText("Confirme a senha:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 223, 125, 27));
        add(lblConfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 360, 28));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(lblNome.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Nome não pode ser vazio!");            
        }
        else if(lblUser.getText().length() == 0){                
            JOptionPane.showMessageDialog(null, "Usuário não pode ficar vazio!");
        }
        else if(lblSenha.getPassword().length == 0){
            JOptionPane.showMessageDialog(null, "Senha não informada!");
        }
        else if(lblConfSenha.getPassword().length == 0){
            JOptionPane.showMessageDialog(null, "Por favor confirme a senha!");
        }
        else if(!(lblSenha.getText().equals(lblConfSenha.getText()))){
            JOptionPane.showMessageDialog(null, "Senhas não conferem!");            
        }
        else {
            boolean res = UserDao.inserir(lblNome.getText(), lblUser.getText(), lblSenha.getText());
            if(res){
                this.parentPane.add("Home", new PanelHome(lblUser.getText()));
                this.parentPane.setSelectedIndex(2);
                this.parentPane.setEnabledAt(0, false);
                this.parentPane.setEnabledAt(1, false);
            }
            else {
                JOptionPane.showMessageDialog(null, "Usuário já está em uso!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField lblConfSenha;
    private javax.swing.JTextField lblNome;
    private javax.swing.JPasswordField lblSenha;
    private javax.swing.JTextField lblUser;
    // End of variables declaration//GEN-END:variables
}
