/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Main;

import telas.Manutencao.Lavoura;

/**
 *
 * @author itzfeltrin
 */
public class PanelHome extends javax.swing.JPanel {

    private String username;
    /**
     * Creates new form PanelAfterLogin
     * @param nome
     */
    public PanelHome(String nome) {
        initComponents();
        this.username = nome;
        lblLogText.setText("Logged in as " + this.username);        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblLogText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAddLavoura = new javax.swing.JButton();
        btnGerLavoura = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setText("jLabel1");

        setLayout(null);

        lblLogText.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        lblLogText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(lblLogText);
        lblLogText.setBounds(343, 0, 350, 39);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setText("Lavoura");
        add(jLabel2);
        jLabel2.setBounds(21, 11, 85, 40);

        btnAddLavoura.setText("Adicionar");
        btnAddLavoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLavouraActionPerformed(evt);
            }
        });
        add(btnAddLavoura);
        btnAddLavoura.setBounds(139, 11, 90, 40);

        btnGerLavoura.setText("Gerenciar");
        btnGerLavoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerLavouraActionPerformed(evt);
            }
        });
        add(btnGerLavoura);
        btnGerLavoura.setBounds(235, 11, 90, 40);
        add(jSeparator1);
        jSeparator1.setBounds(0, 62, 720, 10);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLavouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLavouraActionPerformed
        Lavoura lav = new Lavoura(null, true);
        lav.setVisible(true);
        lav.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAddLavouraActionPerformed

    private void btnGerLavouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerLavouraActionPerformed
        telas.Listagem.Lavoura lav = new telas.Listagem.Lavoura(null, true);
        lav.setVisible(true);
        lav.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnGerLavouraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLavoura;
    private javax.swing.JButton btnGerLavoura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblLogText;
    // End of variables declaration//GEN-END:variables
}

